name: Publish Quarto Notes

on:
  push:
    branches: [ main ]
    paths:
      - 'quarto/**/*.md'
      - 'quarto/**/*.qmd'
      - 'quarto/_quarto.yml'
  workflow_dispatch:  # Allow manual triggering

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.3.450
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter matplotlib pandas scipy networkx pyvis folium
      
      - name: Ensure Quarto config exists
        run: |
          # Create or update _quarto.yml if it doesn't exist
          if [ ! -f quarto/_quarto.yml ]; then
            cat > quarto/_quarto.yml << 'CONFIG'
          project:
            type: website
            output-dir: _site
            
          website:
            title: "Metamechanic Knowledge Base"
            navbar:
              left:
                - href: index.qmd
                  text: Home
                - text: "Categories"
                  menu:
                    - text: "People"
                      href: posts/people.qmd
                    - text: "Books"
                      href: posts/books.qmd
                    - text: "Places"
                      href: posts/places.qmd
                    - text: "Organizations"
                      href: posts/organizations.qmd
                - href: visualizations/index.qmd
                  text: Visualizations
                - href: about.qmd
                  text: About
                  
            sidebar:
              style: "docked"
              search: true
              
          format:
            html:
              theme: cosmo
              css: styles.css
              toc: true
          CONFIG
          fi
          
          # Create index.qmd if it doesn't exist
          if [ ! -f quarto/index.qmd ]; then
            cat > quarto/index.qmd << 'PAGE'
          ---
          title: "Metamechanic Knowledge Base"
          listing:
            contents: posts
            sort: "date desc"
            type: default
            categories: true
            sort-ui: true
            filter-ui: true
          ---

          Welcome to my personal knowledge base.
          PAGE
          fi
      
      - name: Render Quarto project
        working-directory: ./quarto
        run: |
          quarto render || echo "Quarto render failed, creating fallback index.html"
          
          # Fallback if Quarto fails
          if [ ! -f "_site/index.html" ]; then
            mkdir -p _site
            echo "<html><body><h1>Quarto Notes</h1><p>This site will contain your Quarto notes.</p></body></html>" > _site/index.html
          fi
      
      - name: Setup CNAME file
        run: |
          echo "quarto.metamechanic.net" > quarto/_site/CNAME
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: quarto/_site
          branch: gh-pages-quarto
          clean: true
